#!/usr/bin/env bash
#────────────────────────────────────────────────────────────
#   DOTFILE REPO BOOTSTRAP / DEPLOYMENT              
#────────────────────────────────────────────────────────────
#   TODO 1. backup existing files
#        2. for cfg in pwd, stow -R $cfg
#────────────────────────────────────────────────────────────
source ./bin/bin/_head

# mass installation exceptions 
exceptions=("asset" "pc" "root" "vm")

# required packages
reqs=("curl" "wget" "zsh" "neovim" "git" "stow")

# repo's base path
D=$HOME/bm

# title
_t [bmilcs] bootstrap initiated
_o stowing everything includes system configuration files, such as: networkd, iwctl, pacman.conf, etc.

#────────────────────────────────────────────────────────────
# FUNCTIONS
#────────────────────────────────────────────────────────────

izsh() {
  _a zsh
  if [[ ! -f ~/.zsh/completion/_git ]] || [[ ! -f ~/.zsh/completion/git-completion.bash ]] || [[ ! -d ~/.zplugin ]] || [[ ! -d ~/.zsh/completion ]] || [[ ! -d ~/.config/zsh ]] ||  [[ ! -d ~/.zsh/completion ]]; then 
     _o setup required_
     _aa installing: zplugin
     # create directories
     mkdir -p ~/.zplugin ~/.config/zsh/ ~/.zsh/completion
     # install zplugin
     git clone https://github.com/zdharma/zplugin.git ~/.zplugin/bin 
     _s
     # install zsh git completion
     curl -o ~/.zsh/completion/git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
     curl -o ~/.zsh/_git https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
     _s 
  else
    _o setup not required 
    _s
  fi
  }

ivim() {
  _a vim
  if [[ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]]; then
     _o setup required_
     _aa installing vim-plug
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' 
    _s 
  else
    _o setup not required 
    _s 
  fi
  }

#────────────────────────────────────────────────────────────
# MEAT N POTATOES
#────────────────────────────────────────────────────────────

# DISTRO CHECK

_a distro check
source ./root/usr/local/bin/_distro
_s

# INSTALL REQUIRED PACKAGES

_a package prerequisites
_o "${reqs[@]}"

if [[ ${DISTRO} == arch* ]]; then
  pacman -Qi "${reqs[@]}" >/dev/null 2>&1 || ( sudo pacman -Syyy "${reqs[@]}" && _o installed "${reqs[@]}")
elif [[ ${DISTRO} == debian* ]]; then
  dpkg -s "${reqs[@]}" >/dev/null 2>&1 || ( sudo apt-get install "${reqs[@]}" && _o installed "${reqs[@]}")
else
  _e distro not setup yet\! update me\! bootstrap.sh
  exit 1
fi

_s all set 
echo

# GET STARTED

if [[ ${DISTRO} == arch* ]]; then

  # ARCH LINUX

  _ask stow EVERYTHING?

  if [[ $? == 0 ]]; then

    _a ${B}symlink: ${GRN}${B}starting${NC}
    _o distro: $DISTRO 

    # stow /root
    _a system-wide

    _o stowing: root to ${B}/
    sudo stow -t / -R root

    _o stowing: pc to ${B}/
    sudo stow -t / -R pc
    _s 

    _a user-specific
    _o stowing: everything @ home ${B}\~

    # loop through repo
    for dir in $D/*/ ; do

      match=0

      # if looped dir from above = an exception, match!
      for a in "${exceptions[@]}"; do
        [[ $dir == $D/$a/ ]] && match=1
      done

      # if match is found, skip this iteration
      [[ "$match" == 1 ]] && _w skipping $dir && continue

      # not a match && stow it :)
      stow -R $(basename $dir)
      [[ $? -gt 0 ]] && _e $(basename $dir)

    done # end of repo directory loop

  _s 
  fi
  # end of [install everything?]

  # configure shell & vim 
  izsh
  ivim

else

  # DEBIAN

  _a ${B}symlink: ${GRN}${B}starting${NC}
  _o distro: $DISTRO 
  _i minimal install 

  # stow /root
  _a system-wide
  _o stowing: root\/
  _o stowing: vm\/
  sudo stow -t / -R root
  _s 

  _a user-specific
  _o stowing: home ${B}\~

  # stow
  stowee=("bin" "zsh" "vim" "git" "txt")
  stow -R "${stowee[@]}" && _s ${stowee[@]} symlinked

  # set repo url
  git remote set-url origin git@github.com:bmilcs/dotfiles.git 

  # configure vim/zsh
  izsh
  ivim

  # check active shell
  if [[ ! $SHELL == *zsh ]]; then
    # shell != zsh, ask to swap
    _ask swap to ZSH now?
    if [[ $? == 0 ]]; then
      chsh -s /usr/bin/zsh
    else
      _i skipping. reboot recommended!
    fi
  fi

# end of debian
fi

_a bootstrap complete
echo

# exit successfully, despite not having checked lol
exit 0
