#! /bin/sh
#  ▄▄▄▄· • ▌ ▄ ·. ▪  ▄▄▌   ▄▄· .▄▄ ·   ──────────────────────
#  ▐█ ▀█▪·██ ▐███▪██ ██•  ▐█ ▌▪▐█ ▀.   ╔╦╗╔═╗╔╦╗╔═╗╦╦  ╔═╗╔═╗
#  ▐█▀▀█▄▐█ ▌▐▌▐█·▐█·██ ▪ ██ ▄▄▄▀▀▀█▄   ║║║ ║ ║ ╠╣ ║║  ║╣ ╚═╗
#  ██▄▪▐███ ██▌▐█▌▐█▌▐█▌ ▄▐███▌▐█▄▪▐█  ═╩╝╚═╝ ╩ ╚  ╩╩═╝╚═╝╚═╝
#  ·▀▀▀▀ ▀▀  █▪▀▀▀▀▀▀.▀▀▀ ·▀▀▀  ▀▀▀▀   https://dot.bmilcs.com
#────────────────────────────────────────────────────────────
#   bspwm config
#────────────────────────────────────────────────────────────

# launch sxhkd
pgrep sxhkd || sxhkd &

# workspaces
bspc monitor -d dev com web mp3

# colors
bspc config focused_border_color  "#81a1c1"
bspc config normal_border_color   "#4C566A"
bspc config active_border_color   "#eceff4"
bspc config presel_feedback_color "#4C566A"

# window style
bspc config window_gap              2
bspc config top_padding             28
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0

#bspc config automatic_scheme        spiral
#bspc config automatic_scheme      		spiral
#bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child
bspc config border_width            2
bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config single_monocle          true
bspc config focus_follows_pointer   true
bspc config ignore_ewmh_focus       true
bspc config center_pseudo_tiled     true

# window placement
# desktop='^4' state=floating follow=on # state=floating #focus=on #manage=off

bspc rule -a Thunderbird desktop='^2'
bspc rule -a android-messages-desktop desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^2'
bspc rule -a Pidgin desktop='^2' state=floating 
bspc rule -a TelegramDesktop desktop='^2'

# scratchpad
bw=5
bspc rule -a Alacritty:bmpad sticky=on state=floating hidden=on rectangle=2440x488+-$bw+-$bw
    $ddterm_cmd &
alacritty --class=bmpad --title="bmpad" --command zsh -i &

# # autostart [always]
# pgrep polybar || sh $HOME/.config/polybar/launch.sh &
# 
# thunderbird &
# sleep 8
# 
# telegram-desktop &
# sleep 2
# android-messages-desktop &
# sleep 2
# discord &
# sleep 10
# 
# 
# # autostart [initial launch] 
# [ "$1" = 0 ] && {   
#   picom --experimental-backends --config ~/.config/picom/config &
#   nitrogen --restore &
#   pulseaudio --start &
#   unclutter &
#   xcape -e 'Control_L=Escape'
#   }


# graveyard -------------------------------------------------------------------
# 
#  $HOME/.local/bin/bootstrap &
#  bspc wm -l ~/.config/bspwm/canvas.json
#  bspc wm -l ~/.config/bspwm/states/state.json
#  bspc rule -a Thunderbird -o node=@^1:^3:/1 state=floating
#  bspc rule -a TelegramDesktop -o node=@^1:^3:/2/1 state=floating
#  bspc rule -a discord -o node=@^1:^3:/2/2/1 state=floating
#  bspc rule -a android-messages-desktop -o node=@^1:^3:/2/2/2 state=floating
#
