#!/bin/sh

get_icon() {
    case $1 in
        # Icons for weather-icons
        # 宅 卑 喝 墳 奔 
        #🌣 🌤 🌥 🌦  🌧  🌩 🌪
        #                             
        #                             
        #                            
        #                             
        #                           
        #                           
        #                         
        01d) icon="";; # d, clear sky
        01n) icon="";; # n, clear sky
        02d) icon="";; # d, few clouds
        02n) icon="";; # n, few clouds
        03*) icon="";; # scattered clouds
        04*) icon="";; # broken clouds
        09*) icon="";; # shower rain
        10d) icon="";; # d, rain
        10n) icon="";; # n, rain
        11d) icon="";; # d, thunder
        11n) icon="";; # n, thunder
        13d) icon="";; # d, snow
        13n) icon="";; # n, snow
        50d) icon="";; # d, mist
        50n) icon="";; # n, mist
        *) icon=""; # 
        # Icons for Font Awesome 5 Pro
        #01d) icon="";;
        #01n) icon="";;
        #02d) icon="";;
        #02n) icon="";;
        #03d) icon="";;
        #03n) icon="";;
        #04*) icon="";;
        #09*) icon="";;
        #10d) icon="";;
        #10n) icon="";;
        #11*) icon="";;
        #13*) icon="";;
        #50*) icon="";;
        #*) icon="";
    esac

    echo $icon
}


KEY="91a028d98386f02bbf8b86143bac5ad9"
CITY="4955089"
UNITS="imperial"
SYMBOL="宅"



API="https://api.openweathermap.org/data/2.5"

if [ -n "$CITY" ]; then
    if [ "$CITY" -eq "$CITY" ] 2>/dev/null; then
        CITY_PARAM="id=$CITY"
    else
        CITY_PARAM="q=$CITY"
    fi

    weather=$(curl -sf "$API/weather?appid=$KEY&$CITY_PARAM&units=$UNITS")
else
    location=$(curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue)

    if [ -n "$location" ]; then
        location_lat="$(echo "$location" | jq '.location.lat')"
        location_lon="$(echo "$location" | jq '.location.lng')"

        weather=$(curl -sf "$API/weather?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS")
    fi
fi

if [ -n "$weather" ]; then
    weather_desc=$(echo "$weather" | jq -r ".weather[0].description")
    weather_temp=$(echo "$weather" | jq ".main.temp" | cut -d "." -f 1)
    weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")

    echo "$(get_icon "$weather_icon")" "$weather_desc", "$weather_temp$SYMBOL"
fi
