#!/bin/sh

if ! pm=$(checkupdates 2> /dev/null | wc -l ); then
    pm=0
fi

if ! aur=$(yay -Qum 2> /dev/null | wc -l); then
    aur=0
fi

num=$(("$pm" + "$aur"))

if [ "$num" -gt 0 ]; then
    echo "$num"
else
    echo "0"
fi
