#! /bin/sh

pgrep sxhkd || sxhkd &

bspc monitor -d dev msg www mp3 misc

bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          30
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config focused_border_color  "#d8dee9"
bspc config normal_border_color   "#434c5e"
bspc config active_border_color   "#eceff4"
bspc config presel_feedback_color "#98C379"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# export PATH=$PATH:/home/bmilcs/.config/bspwm:/home/bmilcs/bin
# autostart
#$HOME/.local/bin/bootstrap &
pulseaudio --start &
# compositor                           
picom --config ~/.config/picom/config &
# wallpaper   
$HOME/.fehbg &
# polybar                              
/home/bmilcs/.config/polybar/bspwm.sh &

