#! /bin/sh

#
# launch sxhkd
#
pgrep sxhkd || sxhkd &
#
# workspaces
#
bspc monitor -d dev www msg misc
#
# colors
#
bspc config focused_border_color  "#81a1c1"
bspc config normal_border_color   "#4C566A"
bspc config active_border_color   "#eceff4"
bspc config presel_feedback_color "#4C566A"
#
# window style
#
bspc config automatic_scheme        spiral
bspc config window_gap              6
bspc config top_padding             50
bspc config bottom_padding          25
bspc config right_padding          25
bspc config left_padding          25

bspc config border_width            2
bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config single_monocle          true
bspc config focus_follows_pointer   true
bspc config ignore_ewmh_focus       true
bspc config center_pseudo_tiled     true

#
# window placement
#
bspc rule -a Thunderbird desktop='^3'
bspc rule -a android-messages-desktop desktop='^3'
bspc rule -a Firefox desktop='^3'
bspc rule -a discord desktop='^3'
bspc rule -a Pidgin desktop='^3' state=floating 
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^3'

#state=floating
#focus=on
#manage=off
#
# autostart
#
[ "$1" = 0 ] && {   # only on bspwm start (not reload)
  pidgin &
  discord &
  thunderbird &
  telegram-desktop &
  android-messages-desktop &
  pulseaudio --start &
  picom --config ~/.config/picom/config &
  nitrogen --restore &
  /home/bmilcs/.config/polybar/bspwm.sh &
  unclutter &
}
#$HOME/.local/bin/bootstrap &
